config/routes.rb
Rails.application.routes.draw do
devise_for :users
root to: 'homes#top'
get 'homes/about' => "homes#about", as: 'about'

resources :books
resources :users, only: [:show, :edit, :update, :index ]

get 'homes/about' => "homes#about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  has_one_attached :profile_image, dependent: :destroy
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true ,length: {maximum: 200}
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, length: {in:2..20} ,uniqueness: true
  validates :introduction ,length: {maximum: 50}
  
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_up_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully."
    user_path(current_user.id)
  end

  def after_sign_in_path_for(resource)
    flash[:notice] = "signed in successfully."
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])

  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def index
    @user = current_user 
    @book = Book.new
    @books = Book.all
  end

  def create
    @user = current_user
    @book = Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
  if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
  else
    render :index
  end
  end

  def show
    @user = User.find(params[:id])
    
    @books = @user.books
    @book = Book.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
  if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
  else
    render :edit
  end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    user = User.find(params[:id])
  unless user.id == current_user.id
    redirect_to users_path
  end
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
  if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
  else
    render :edit
  end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_bottom.html.erb
      </div>
    </div>
  </div>
</main>

app/views/books/_list.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag user.get_profile_image(100,100) %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      
      <div class="btn btn-outline-secondary btn-block" >
        <% if user.id == current_user.id %>
          <%= link_to edit_user_path(user), class: "btn",method: :get do %>
            <i class="fa-solid fa-user-gear"></i>
          <% end %>
        <% end %>
      </div>
    
      <h2 class="mt-3" >New book</h2>
      <%= form_with model: book do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body %>
        </div>

        <div class="form-group ">
          <%= f.submit 'Create Book',class: "btn btn-success"  %>
        </div>
      <% end %>
      </div>
      <div class="col-md-8 offset-md-1 ">

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>Editing Book</h2>
        <% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this obj from being saved:
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <div>
          <%= form_with model: @book do |f| %>
            <div class="form-group">
              <label for="inputTitle">Title</label>
              <div>
                <%= f.text_field :title, autofocus: true%>
              </div>
            </div>
            <div class="form-group">
              <label for="Opinion">Opinion</label>
              <div>
              <%= f.text_field :body %>
              </div>
            </div>
            <div class="form-group"></div>
              <%= f.submit "Update Book", class: "btn btn-success" %>
            </div>
          <% end %>
          <%= link_to 'Show', book_path(@book.id) %> |
          <%= link_to 'Back', books_path %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'list', user: @user, book: @book %>
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= image_tag book.user.get_profile_image(100,100) %></td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
 <%= render 'bottom' %>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<%= render 'list', user: @user, book: @book %>
  <h2>Book detail</h2>
  <table class="table table-hover table-inverse">
    <thead>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= image_tag book.user.get_profile_image(100,100) %></td>
          <td><%= link_to book.user.name, user_path(@user.id) %></td>
          <td><%= link_to book.title, book_path(@book.id) %></td>
          <td><%= book.body %></td>
          <% if @user == current_user %>
          <td><%= link_to "Edit", edit_book_path(book.id), class: "btn btn-success" %></td>
          <td><%= link_to "Delete", book_path(book.id), class: "btn btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
          </tr>
        <% end %>
        <% end %>
    </tbody>
  </table>
<%= render 'books/bottom' %>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<%= flash[:notice] =%>

<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!!</h1>
      <p>In <i class="fa-solid fa-book"></i><strong>Bookers</strong></p>
      <p>you can share and exchange your opinions, inpressions, and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <li class="btn btn-info btn-sm btn-block mb-3 sign_in">
            <%= link_to "Log in", new_user_session_path, class: 'text-light' %>
          </li>
        </div>
        <div class="row">
          <li class="btn btn-success btn-sm btn-block sign_up">
            <%= link_to "Sign up", new_user_registration_path, class: 'text-light' %>
          </li>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">

   <script src="https://kit.fontawesome.com/76f411fe92.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <li class="navbar-brand">
        <%= link_to "Bookers", root_path, class: 'text-light' %>
          </li>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-link text-light">
                <%= link_to root_path, class: 'nav-link text-light', method: :get do %>
                  <i class="fa-solid fa-house"></i> Home
                <% end %>
              </li>
              <li class="nav-link text-light">
                <%= link_to users_path, class: 'nav-link text-light', method: :get do %>
                  <i class="fa-sharp fa-solid fa-users"></i> Users
                <% end %>
              </li>
              <li class="nav-link text-light">
                <%= link_to  books_path, class: 'nav-link text-light', method: :get do %>
                  <i class="fa-solid fa-book-open"></i> Books
                <% end %>
              </li>
              <li class="nav-link text-light">
                <%= link_to destroy_user_session_path, class: 'nav-link text-light', method: :delete do %>
                  <i class="fa-solid fa-right-from-bracket"></i> Log out
                <% end %>
              </li>
              
            <% else %>
             <li class="nav-link text-light">
                <%= link_to root_path, class: 'nav-link text-light', method: :get do %>
                  <i class="fa-solid fa-house"></i> Home
                <% end %>
              <li class="nav-link text-light">
                <%= link_to about_path, class: 'nav-link text-light', method: :get do %>
                  <i class="fa-solid fa-link"></i> About
                <% end %>
              </li>
              <li class="nav-link text-light">
                <%= link_to new_user_registration_path, class: 'nav-link text-light', method: :get do %>
                  <i class="fa-solid fa-user-plus"></i> Sign up
                <% end %>
              </li>
              <li class="nav-link text-light">
                <%= link_to  new_user_session_path, class: 'nav-link text-light', method: :get do %>
                  <i class="fa-solid fa-right-to-bracket"></i> Log in
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>


    <%= yield %>
  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>

  </body>
</html>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
        <% if @user.errors.any? %>
        <%= @user.errors.count %>errors prohibited this obj from being saved:
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <%= form_with model: @user do |f| %>
          <div class="form-group">
            <label for="inputName">Name</label>
            <div>
              <%= f.text_field :name, autofocus: true, id:"inputName"%>
            </div>
          </div>
          <div class="form-group">
            <label for="inputImage">Image</label>
            <div>
              <%= f.file_field :profile_image, accept: "image/*" %>
            </div>
          </div>
          <div class="form-group">
            <label for="inputIntroduction">Introduction</label>
            <div>
              <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction"%>
            </div>
          </div>
          <div class="form-group">
            <div>
              <%= f.submit "Update User" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<%= render 'books/list', user: @user, book: @book %>
  <h2>Users</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(100,100) %></td>
          <td><%= user.name %></td>
          <td><%= link_to 'Show', user_path(@user.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<%= render 'books/bottom' %>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] =%>
</div>

<%= render 'books/list', user: @user, book: @book %>
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
        <td><%= image_tag book.user.get_profile_image(100,100) %></td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%= render 'books/bottom' %>